first_contact: "conductor_agent"
toolExecutorType: "default"
dispatcherType: "synchronous"
# customModules:
agents:
  - name: "conductor_agent"
    type: "conductor"
    llm: "gpt-4-o-openai"
    maxTrials: 10
    prompt:
      type: "conductor_prompt"
      location: "agents/conductor_agent"
      userPromptArgumentClass: "ConductorUserPromptArgument"
      systemPromptArgumentClass: "ConductorSystemPromptArgument"
      longtermMemoryClass: "MyConductorLongtermMemory"
      canFinalizeName: "can_finalize"
    topics:
      - "first_agent"
      - "second_agent"
    finalizerName: "finalizer_agent"
  - name: "first_agent"
    type: "multistep"
    llm: "gpt-4-o-openai"
    maxReasoningSteps: 25
    prompt:
      type: "multistep_prompt"
      location: "agents/first_agent"
      systemPromptArgumentClass: "FirstSystemPromptArgument"
      userPromptArgumentClass: "FirstUserPromptArgument"
      isValidName: "is_valid"
      isFinalName: "is_final"
    tools:
      - "example_tool1"
      - "example_tool2"
    topics:
      - "conductor_agent"
  - name: "second_agent"
    type: "multistep"
    llm: "gpt-4-o-openai"
    prompt:
      type: "multistep_prompt"
      location: "agents/second_agent"
      systemPromptArgumentClass: "SecondSystemPromptArgument"
      userPromptArgumentClass: "SecondUserPromptArgument"
      isValidName: "is_valid"
      isFinalName: "is_final"
    tools:
      - "example_tool1"
      - "example_tool2"
    topics:
        - "conductor_agent"

llms:
  - name: "gpt-4-o-openai"
    type: "openai"
    modelName: "gpt-4o"
    modelMaxTokens: 8192
    apiKey: "${OPENAI_API_KEY}"

tools:
  - name: "example_tool1"
    functionName: "my_func1"
    modulePath: "my_tools/example_tools.py"
  - name: "example_tool2"
    functionName: "my_func2"
    modulePath: "my_tools/example_tools.py"
    configs:
      foo: "bar"
      baz: "qux"
toolDependencies:
  someExternalDependency:
    userName: "Jane"
    street: "Maint st."