name: Deploy Website

on:
  push:
    branches:
      - main  # Deploy only on changes pushed to the main branch
    paths:
      - 'website/**'  # Trigger only if files in the website directory change

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive  # Initialize and update submodules

      # Step 2: Set up Hugo
      - name: Setup Hugo
        uses: actions/setup-hugo@v3
        with:
          hugo-version: 'latest'  # Use the latest Hugo version

      # Step 3: Build the Hugo website
      - name: Build the website
        run: hugo --source website  # Specify the source directory for Hugo

      # Step 4: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # Deploy to the gh-pages branch
          folder: website/public  # Folder containing the built site
          clean: true  # Clean the target branch before deploying
